// Code generated by "stringer -linecomment -type Kind"; DO NOT EDIT.

package sym

import "strconv"

const _Kind_name = "1280828486888a8c94 Def96 Def2overlay"

var _Kind_map = map[Kind]string{
	1:   _Kind_name[0:1],
	2:   _Kind_name[1:2],
	128: _Kind_name[2:4],
	130: _Kind_name[4:6],
	132: _Kind_name[6:8],
	134: _Kind_name[8:10],
	136: _Kind_name[10:12],
	138: _Kind_name[12:14],
	140: _Kind_name[14:16],
	148: _Kind_name[16:22],
	150: _Kind_name[22:29],
	152: _Kind_name[29:36],
}

func (i Kind) String() string {
	if str, ok := _Kind_map[i]; ok {
		return str
	}
	return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
}
