// Code generated by "stringer -linecomment -type Kind"; DO NOT EDIT.

package sym

import "strconv"

const _Kind_name = "overlay"

var _Kind_index = [...]uint8{0, 7}

func (i Kind) String() string {
	i -= 152
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i+152), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
