// Code generated by "stringer -linecomment -type Mod"; DO NOT EDIT.

package sym

import "strconv"

const _Mod_name = "PTRFCNARY"

var _Mod_index = [...]uint8{0, 3, 6, 9}

func (i Mod) String() string {
	i -= 1
	if i >= Mod(len(_Mod_index)-1) {
		return "Mod(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Mod_name[_Mod_index[i]:_Mod_index[i+1]]
}
