// Code generated by "stringer -linecomment -type Type"; DO NOT EDIT.

package sym

import "strconv"

const (
	_Type_name_0 = "STRUCT"
	_Type_name_1 = "UCHARUSHORTUINTULONG"
)

var (
	_Type_index_1 = [...]uint8{0, 5, 11, 15, 20}
)

func (i Type) String() string {
	switch {
	case i == 8:
		return _Type_name_0
	case 12 <= i && i <= 15:
		i -= 12
		return _Type_name_1[_Type_index_1[i]:_Type_index_1[i+1]]
	default:
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
