// Code generated by "stringer -linecomment -type BaseType"; DO NOT EDIT.

package c

import "strconv"

const _BaseType_name = "voidcharshortintlongunsigned charunsigned shortunsigned intunsigned long"

var _BaseType_index = [...]uint8{0, 4, 8, 13, 16, 20, 33, 47, 59, 72}

func (i BaseType) String() string {
	i -= 1
	if i >= BaseType(len(_BaseType_index)-1) {
		return "BaseType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _BaseType_name[_BaseType_index[i]:_BaseType_index[i+1]]
}
