// Code generated by "stringer -linecomment -type StorageClass"; DO NOT EDIT.

package c

import "strconv"

const _StorageClass_name = "autoexternstaticregistertypedef"

var _StorageClass_index = [...]uint8{0, 4, 10, 16, 24, 31}

func (i StorageClass) String() string {
	i -= 1
	if i >= StorageClass(len(_StorageClass_index)-1) {
		return "StorageClass(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _StorageClass_name[_StorageClass_index[i]:_StorageClass_index[i+1]]
}
